apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: akuity
  labels:
    kargo.akuity.io/cred-type: git
    kargo.akuity.io/namespace: kargo-creds
type: Opaque
data:
  repoURL:  aHR0cHM6Ly9naXRodWIuY29tL215LW9yZy9teS1yZXBvLmdpdA==  # "https://github.com/my-org/my-repo.git"
  username: bXktdXNlcm5hbWU=                                      # "my-username"
  password: bXktZ2hwLXRva2VuLW9yLXBhdA==                          # "my-ghp-token-or-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-charts-creds
  namespace: akuity
  labels:
    kargo.akuity.io/cred-type: helm
    kargo.akuity.io/namespace: kargo-creds
type: Opaque
data:
  repoURL:  aHR0cHM6Ly9jaGFydHMubXkuZG9tYWluLmNvbQ==             # "https://charts.my.domain.com"
  username: aGVsbS11c2Vy                                         # "helm-user"
  password: c3VwZXItc2VjcmV0LXBhc3M=                             # "super-secret-pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-creds
  namespace: akuity
  labels:
    kargo.akuity.io/cred-type: image
    kargo.akuity.io/namespace: akuity
type: Opaque
data:
  repoURL:  cmVnaXN0cnkubXkuZG9tYWluLmNvbS9teS1hcHAvY29udGFpbmVy # "registry.my.domain.com/my-app/container"
  username: cmVnaXN0cnktaW8tYXBw                                 # "registry-io-app"
  password: c3VwZXItc2VjcmV0LXRva2Vu                             # "super-secret-token"
